name: build

on:
  pull_request:
    branches:
      - main
    paths:
      - 'source/**/*'
      - 'dub.json'
      - 'dub.selections.json'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  script:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        dc: [dmd-master] # dmd-latest, ldc-latest, ldc-master
        arch: [x86_64] # x86
        build_type: [debug, release, release-debug, release-inline]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: Run pre build script
        if: runner.os == 'Linux'
        run: .github/workflows/pre-build.sh

      - name: Build static library
        run: dub build --build=${{ matrix.build_type }} --config=static --arch=${{ matrix.arch }} --parallel --build-mode=singleFile --force -v

      # Don't build dynamic libraries using DMD for Windows
      - name: Build dynamic library
        if: runner.os != 'Windows' || (runner.os == 'Windows' && !(startsWith(matrix.dc, 'dmd-')))
        run: dub build --build=${{ matrix.build_type }} --config=shared --arch=${{ matrix.arch }} --parallel --build-mode=singleFile --force -v
