name: docs-workflow

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build-and-tests:
    strategy:
      matrix:
        docs_type: [ddox, docs]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: dmd-master

      - name: Build documentation
        run: dub build --build=${{ matrix.docs_type }}
