name: docs

on:
  pull_request:
    branches:
      - main
    paths:
      - 'source/**'
      - 'dub.json'
      - 'dub.selections.json'
      # This file
      - '.github/workflows/docs.yml'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  script:
    strategy:
      matrix:
        docs_type: [ddox, docs, adrdox]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: dmd-master

      - name: Build documentation
        if: matrix.docs_type != 'adrdox'
        run: dub build --build=${{ matrix.docs_type }}

      - name: Build documentation
        if: matrix.docs_type == 'adrdox'
        run: dub run adrdox -- source
